spring:

  datasource:
    url: jdbc:mysql://localhost:3306/solid
    username: root
    password: LetMeIn!123

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  sql:
    init:
      schema-locations: classpath:schema.sql
      mode: always